apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafahs-tech
  namespace: rafaelhs-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rafahs-tech
  template:
    metadata:
      labels:
        app: rafahs-tech
    spec:
      containers:
        - name: rafahs-tech
          image: rafaelhs/rafaelhs-tech:latest
          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: rafahs-tech-svc
  namespace: rafaelhs-tech
spec:
  type: ClusterIP
  selector:
    app: rafahs-tech
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rafahs-tech-ingress
  namespace: rafaelhs-tech
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: rafaelhs-tech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rafahs-tech-svc
                port:
                  number: 80
