apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafahs-tech
  namespace: rafahs-tech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rafahs-tech
  template:
    metadata:
      labels:
        app: rafahs-tech
    spec:
      containers:
      - name: rafahs-tech
        image: rafaelhs/meu-site-angular:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rafahs-tech-svc
  namespace: rafahs-tech
spec:
  type: ClusterIP
  selector:
    app: rafahs-tech
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rafahs-tech-ingress
  namespace: rafahs-tech
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: ec2-44-202-101-227.compute-1.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rafahs-tech-svc
            port:
              number: 80
