# .github/workflows/deploy-to-ec2-k3s.yml
name: Deploy to EC2 + K3s

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build e push
        run: |
          docker build -t rafaelhs/rafahs-tech:latest .
          docker push rafaelhs/rafahs-tech:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull da imagem no servidor
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@{{ secrets.EC2_HOST }} "sudo k3s ctr images pull docker.io/rafaelhs/rafahs-tech:latest"

      - name: Deploy no K3s
        run: |
          scp -o StrictHostKeyChecking=no app-deploy.yaml ubuntu@{{ secrets.EC2_HOST }}:~/app-deploy.yaml
          ssh -o StrictHostKeyChecking=no ubuntu@{{ secrets.EC2_HOST }} "sudo k3s kubectl apply -f ~/app-deploy.yaml && sudo k3s kubectl rollout restart deployment rafahs-tech"
