# .github/workflows/deploy-to-ec2-k3s.yml
name: Deploy to EC2 + K3s

#on:
#push:
#branches:
#- master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
          --platform linux/amd64 \
          --tag rafaelhs/rafaelhs-tech:latest \
          --push .

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Pull da imagem no servidor
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} \
          "sudo k3s ctr images pull docker.io/rafaelhs/rafaelhs-tech:latest"

      - name: Deploy no K3s
        run: |
          scp -o BatchMode=yes -o StrictHostKeyChecking=no manifests/rafaelhs-tech-deploy.yaml ubuntu@${{ secrets.EC2_HOST }}:~/rafaelhs-tech-deploy.yaml
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} \
          "sudo k3s kubectl apply -f ~/rafaelhs-tech-deploy.yaml && sudo k3s kubectl rollout restart deployment rafahs-tech -n rafaelhs-tech"
