# .github/workflows/deploy-to-ec2-k3s.yml
name: Deploy to EC2 + K3s

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 1) Log in no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2) Build & push da imagem
      - name: Build and push Docker image
        run: |
          docker build -t rafaelhs/rafahs-tech:latest .
          docker push rafaelhs/rafahs-tech:latest

      # 3) Inicia o ssh-agent
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # passo A: só faz o pull da imagem
      - name: Pull image on EC2
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} \
            "sudo k3s ctr images pull docker.io/rafaelhs/rafahs-tech:latest"

    # passo B: aplica manifests (rápido)
      - name: Apply manifests on EC2
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} \
            "sudo k3s kubectl apply -R -f ~/apps/rafahs-tech \
               --validate=false \
              --request-timeout=60s && \
            sudo k3s kubectl -n rafahs-tech rollout restart deployment/rafahs-tech"
